import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Notification from '@/Components/Notification';
import Footer from "@/Components/Footer";
import Navbar from '@/Components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Notification/> */}
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
